import type { Product } from "./types";

const g = (from: string, to: string) => `linear-gradient(155deg, ${from}, ${to})`;

export const products: Product[] = [
  {
    id: "mughal",
    name: "Mughal",
    category: "premium",
    gender: "men",
    sections: ["trending", "bestsellers"],
    price: 3100,
    originalPrice: 5000,
    discountPct: 38,
    art: g("#e7cfa4", "#6b3e1b"),
    artHover: g("#c9a771", "#4a280f"),
    rating: 4.8,
    reviews: 312,
    description: "A royal composition of oud, saffron and warm amber — fit for a coronation.",
    subtitle: "Extrait de Parfum",
    notes: { top: "Saffron, pink pepper", heart: "Oud, Bulgarian rose", base: "Amber, sandalwood" },
  },
  {
    id: "hajj",
    name: "Hajj Perfume",
    category: "premium",
    gender: "unisex",
    sections: ["trending", "bestsellers", "new"],
    price: 3100,
    originalPrice: 5000,
    discountPct: 38,
    art: g("#f3e6cc", "#9a7a48"),
    artHover: g("#e3cc99", "#745a33"),
    rating: 4.9,
    reviews: 418,
    description: "An alcohol-free attar with pure oud, musk and rose — inspired by the sacred journey.",
    subtitle: "Attar · 12 ml",
    notes: { top: "Rose, citrus zest", heart: "Oud, musk", base: "Sandalwood, amber" },
    variants: ["6ml roll-on", "12ml roll-on"],
  },
  {
    id: "sultan",
    name: "Sultan",
    category: "premium",
    gender: "men",
    sections: ["bestsellers"],
    price: 3500,
    originalPrice: 5600,
    discountPct: 38,
    art: g("#caa06b", "#3f2110"),
    artHover: g("#b0895a", "#2a150a"),
    rating: 4.7,
    reviews: 186,
    description: "Rich leather and smoked oud laced with cardamom — a throne-room presence.",
    subtitle: "Oud Extrait · 50 ml",
    notes: { top: "Cardamom, bergamot", heart: "Leather, oud", base: "Tonka, patchouli" },
  },
  {
    id: "noor",
    name: "Noor",
    category: "premium",
    gender: "women",
    sections: ["trending", "new"],
    price: 2800,
    originalPrice: 4500,
    discountPct: 38,
    art: g("#f7d7d9", "#9a4a55"),
    artHover: g("#e8bec1", "#7a3642"),
    rating: 4.6,
    reviews: 204,
    description: "A luminous floral — Damask rose, jasmine and white musk.",
    subtitle: "Eau de Parfum · 100 ml",
    notes: { top: "Bergamot, lychee", heart: "Damask rose, jasmine", base: "White musk, cedar" },
  },
  {
    id: "shahi-attar",
    name: "Shahi Oud Attar",
    category: "attar",
    gender: "unisex",
    sections: ["bestsellers", "trending"],
    price: 1850,
    originalPrice: 3000,
    discountPct: 38,
    art: g("#a97339", "#2a1105"),
    artHover: g("#8b5d2a", "#1a0802"),
    rating: 4.9,
    reviews: 512,
    description: "A pure Cambodi oud attar aged for 6 years — deeply resinous.",
    subtitle: "Oud Attar · 12 ml",
    notes: { top: "Saffron", heart: "Pure oud", base: "Amber, labdanum" },
    variants: ["3ml", "6ml", "12ml"],
  },
  {
    id: "arabian-musk",
    name: "Arabian Musk Attar",
    category: "attar",
    gender: "unisex",
    sections: ["new"],
    price: 1650,
    originalPrice: 2700,
    discountPct: 39,
    art: g("#f1e2c7", "#b99361"),
    artHover: g("#ddcaa3", "#96754a"),
    rating: 4.7,
    reviews: 221,
    description: "Creamy white musk with a breath of jasmine — soft, skin-close, gorgeous.",
    subtitle: "Musk Attar · 12 ml",
    notes: { top: "Orange blossom", heart: "White musk, jasmine", base: "Sandalwood" },
    variants: ["6ml", "12ml"],
  },
  {
    id: "french-jasmine",
    name: "French Jasmine Attar",
    category: "attar",
    gender: "women",
    sections: ["new"],
    price: 1950,
    originalPrice: 3200,
    discountPct: 39,
    art: g("#fff3dc", "#c9a05b"),
    artHover: g("#f0dfbb", "#a8823f"),
    rating: 4.6,
    reviews: 148,
    description: "Grasse jasmine absolute layered over Mysore sandalwood.",
    subtitle: "Floral Attar · 12 ml",
    notes: { top: "Neroli", heart: "Jasmine absolute", base: "Mysore sandalwood" },
  },
  {
    id: "mukhalat-royal",
    name: "Mukhalat Royal",
    category: "attar",
    gender: "unisex",
    sections: ["bestsellers"],
    price: 2200,
    originalPrice: 3600,
    discountPct: 39,
    art: g("#b88357", "#3d1c0a"),
    artHover: g("#9a6a42", "#2a1107"),
    rating: 4.8,
    reviews: 277,
    description: "A master blend of oud, rose, saffron and amber — layered for hours of projection.",
    subtitle: "Mukhalat · 6 ml",
    notes: { top: "Saffron, rose petals", heart: "Oud, amber", base: "Patchouli, musk" },
  },
  {
    id: "bakhoor-wood",
    name: "Bakhoor Wood",
    category: "bakhoor",
    gender: "unisex",
    sections: ["trending", "bestsellers"],
    price: 950,
    originalPrice: 1500,
    discountPct: 37,
    art: g("#7a4a23", "#2b130a"),
    artHover: g("#603717", "#1a0a05"),
    rating: 4.7,
    reviews: 163,
    description: "Slow-burning oud-infused wood chips. Fills a room in minutes.",
    subtitle: "Oud Wood · 40 g",
    notes: { top: "—", heart: "Oud wood, agarwood", base: "Smoked amber" },
    variants: ["40g", "80g"],
  },
  {
    id: "bakhoor-burner",
    name: "Brass Bakhoor Burner",
    category: "bakhoor",
    gender: "unisex",
    sections: ["new"],
    price: 2400,
    originalPrice: 3500,
    discountPct: 31,
    art: g("#e6c07a", "#9a6a1f"),
    artHover: g("#cda464", "#80540f"),
    rating: 4.9,
    reviews: 91,
    description: "Hand-hammered brass mabkhara with electric heating base.",
    subtitle: "Incense Burner",
    notes: { top: "—", heart: "—", base: "—" },
  },
  {
    id: "soft-citrus",
    name: "Citrus Breeze",
    category: "affordable",
    gender: "unisex",
    sections: ["new", "trending"],
    price: 1200,
    originalPrice: 2000,
    discountPct: 40,
    art: g("#fff2b3", "#cdbd4f"),
    artHover: g("#f0e298", "#a99736"),
    rating: 4.4,
    reviews: 88,
    description: "Bright bergamot and yuzu over white musk — a clean daily driver.",
    subtitle: "Eau de Toilette · 75 ml",
    notes: { top: "Bergamot, yuzu", heart: "Neroli", base: "White musk, cedar" },
  },
  {
    id: "oceanic",
    name: "Ocean Mist",
    category: "affordable",
    gender: "men",
    sections: ["bestsellers"],
    price: 1400,
    originalPrice: 2200,
    discountPct: 36,
    art: g("#c7e1ef", "#3e6c91"),
    artHover: g("#a8cfe2", "#2b4e6b"),
    rating: 4.3,
    reviews: 142,
    description: "Salty air, driftwood and a pinch of ambroxan — summer on the coast.",
    subtitle: "Eau de Toilette · 75 ml",
    notes: { top: "Sea salt, mandarin", heart: "Driftwood", base: "Ambroxan, musk" },
  },
  {
    id: "rose-oud",
    name: "Rose Oud",
    category: "premium",
    gender: "women",
    sections: ["new", "trending"],
    price: 3200,
    originalPrice: 5200,
    discountPct: 38,
    art: g("#ea9aa8", "#6c2238"),
    artHover: g("#c97d8b", "#4d1825"),
    rating: 4.8,
    reviews: 196,
    description: "Turkish rose meets smoked oud — the timeless pairing, perfected.",
    subtitle: "Parfum · 50 ml",
    notes: { top: "Rose petals", heart: "Oud, raspberry", base: "Amber, patchouli" },
  },
  {
    id: "winter-musk",
    name: "Winter Musk",
    category: "affordable",
    gender: "unisex",
    sections: ["trending"],
    price: 1350,
    originalPrice: 2100,
    discountPct: 36,
    art: g("#e4dcd0", "#7a6a55"),
    artHover: g("#cfc4b1", "#544532"),
    rating: 4.5,
    reviews: 121,
    description: "Cashmere musk, vanilla and soft woods — a hug in a bottle.",
    subtitle: "Eau de Parfum · 75 ml",
    notes: { top: "Aldehyde, bergamot", heart: "Cashmere musk, vanilla", base: "Sandalwood" },
  },
  {
    id: "pure-oud-attar",
    name: "Pure Oud Attar",
    category: "attar",
    gender: "men",
    sections: ["bestsellers", "new"],
    price: 4800,
    originalPrice: 7800,
    discountPct: 38,
    art: g("#8a5a2a", "#1f0d04"),
    artHover: g("#714726", "#140701"),
    rating: 4.9,
    reviews: 88,
    description: "Undiluted Hindi oud — an investment piece for the oud connoisseur.",
    subtitle: "Pure Oud Attar · 3 ml",
    notes: { top: "Saffron", heart: "Pure Hindi oud", base: "Resinous woods" },
    variants: ["1.5ml", "3ml"],
  },
];

export const productById = (id: string) => products.find((p) => p.id === id);
