// Product catalogue — Maison Velour
// Prices are in Pakistani Rupees (PKR).
// Each product has a color palette used to tint its SVG bottle illustration.
window.PRODUCTS = [
  {
    id: "noir-01",
    name: "Nuit d'Or",
    tagline: "Amber · Oud · Saffron",
    category: "Oriental",
    gender: "Unisex",
    price: 52000,
    oldPrice: null,
    badge: "Bestseller",
    colors: { liquid: "#5a2c18", cap: "#2a1b0f", label: "#b8935b" },
    sizes: [
      { ml: 30, price: 26500 },
      { ml: 50, price: 40500 },
      { ml: 100, price: 52000 },
    ],
    top: ["Saffron", "Bergamot"],
    heart: ["Bulgarian Rose", "Jasmine"],
    base: ["Oud", "Amber", "Vanilla"],
    description:
      "A midnight elixir of aged oud and liquid amber, veiled in saffron and rose. Opulent, warm and unmistakably nocturnal.",
  },
  {
    id: "verdant-02",
    name: "Jardin Vert",
    tagline: "Fig · Vetiver · Green Tea",
    category: "Green",
    gender: "Women",
    price: 40500,
    oldPrice: 49000,
    badge: "New",
    colors: { liquid: "#9bb08a", cap: "#2e3d2a", label: "#d9e4c8" },
    sizes: [
      { ml: 30, price: 21000 },
      { ml: 50, price: 32000 },
      { ml: 100, price: 40500 },
    ],
    top: ["Fig Leaf", "Lemon"],
    heart: ["Green Tea", "White Lily"],
    base: ["Vetiver", "Cedarwood"],
    description:
      "Sunlit Mediterranean gardens bottled. Crushed fig leaves and dewy jasmine settle onto smoky vetiver for a crisp, contemplative finish.",
  },
  {
    id: "ocean-03",
    name: "Mer Azure",
    tagline: "Sea Salt · Iris · Driftwood",
    category: "Aquatic",
    gender: "Men",
    price: 46000,
    oldPrice: null,
    badge: null,
    colors: { liquid: "#8fb8cc", cap: "#1a2f3b", label: "#cfe3ec" },
    sizes: [
      { ml: 30, price: 24000 },
      { ml: 50, price: 35000 },
      { ml: 100, price: 46000 },
    ],
    top: ["Sea Salt", "Pink Pepper"],
    heart: ["Iris", "Lavender"],
    base: ["Driftwood", "Ambergris"],
    description:
      "Atlantic winds at first light — bright citrus salt, powdery iris and the warmth of driftwood smoothed by the tide.",
  },
  {
    id: "rose-04",
    name: "Rosa Venezia",
    tagline: "Damask Rose · Patchouli · Musk",
    category: "Floral",
    gender: "Women",
    price: 54500,
    oldPrice: null,
    badge: "Limited",
    colors: { liquid: "#c98a96", cap: "#3a1620", label: "#f2d6dc" },
    sizes: [
      { ml: 30, price: 29500 },
      { ml: 50, price: 43500 },
      { ml: 100, price: 54500 },
    ],
    top: ["Raspberry", "Pink Pepper"],
    heart: ["Damask Rose", "Peony"],
    base: ["Patchouli", "White Musk"],
    description:
      "A velvet bouquet of Turkish rose, plush peony and ripe berries atop a base of patchouli and skin-warm musk.",
  },
  {
    id: "smoke-05",
    name: "Fumée Noire",
    tagline: "Leather · Smoke · Birch Tar",
    category: "Woody",
    gender: "Men",
    price: 59000,
    oldPrice: null,
    badge: null,
    colors: { liquid: "#3b2a22", cap: "#0a0605", label: "#a38672" },
    sizes: [
      { ml: 30, price: 31000 },
      { ml: 50, price: 47500 },
      { ml: 100, price: 59000 },
    ],
    top: ["Black Pepper", "Bergamot"],
    heart: ["Leather", "Cypress"],
    base: ["Birch Tar", "Guaiac Wood"],
    description:
      "A smouldering leather accord wrapped in cypress smoke. For those who dress in ink and speak in silence.",
  },
  {
    id: "citrus-06",
    name: "Neroli Solaire",
    tagline: "Neroli · Bitter Orange · White Musk",
    category: "Citrus",
    gender: "Unisex",
    price: 38000,
    oldPrice: null,
    badge: null,
    colors: { liquid: "#eccb6b", cap: "#7a5710", label: "#fff0c8" },
    sizes: [
      { ml: 30, price: 19500 },
      { ml: 50, price: 29500 },
      { ml: 100, price: 38000 },
    ],
    top: ["Bitter Orange", "Mandarin"],
    heart: ["Neroli", "Orange Blossom"],
    base: ["White Musk", "Benzoin"],
    description:
      "Capri at noon. Sun-warmed bitter orange and waxy neroli softened by sheer musk for a radiant, effortless glow.",
  },
  {
    id: "gourmand-07",
    name: "Cocoa Velvet",
    tagline: "Cocoa · Tonka · Vanilla",
    category: "Gourmand",
    gender: "Unisex",
    price: 49000,
    oldPrice: null,
    badge: "Bestseller",
    colors: { liquid: "#6a3f29", cap: "#1e110b", label: "#d4ae80" },
    sizes: [
      { ml: 30, price: 25000 },
      { ml: 50, price: 38000 },
      { ml: 100, price: 49000 },
    ],
    top: ["Bitter Almond", "Pink Pepper"],
    heart: ["Cocoa Absolute", "Rose"],
    base: ["Tonka Bean", "Vanilla", "Sandalwood"],
    description:
      "A hushed confection of dark cocoa and tonka bean, laced with rose and polished by creamy sandalwood.",
  },
  {
    id: "iris-08",
    name: "Iris Parme",
    tagline: "Iris · Violet · Suede",
    category: "Floral",
    gender: "Women",
    price: 61500,
    oldPrice: null,
    badge: "Limited",
    colors: { liquid: "#a590c0", cap: "#2d1f3d", label: "#e4d4f0" },
    sizes: [
      { ml: 30, price: 32000 },
      { ml: 50, price: 49000 },
      { ml: 100, price: 61500 },
    ],
    top: ["Violet Leaf", "Green Mandarin"],
    heart: ["Iris Pallida", "Heliotrope"],
    base: ["Suede", "Cashmeran", "Ambrette"],
    description:
      "A powdered reverie of rare Tuscan iris and sugared violet, landing softly on buttery suede.",
  },
  {
    id: "spice-09",
    name: "Safran Royal",
    tagline: "Saffron · Cardamom · Leather",
    category: "Oriental",
    gender: "Unisex",
    price: 67000,
    oldPrice: null,
    badge: null,
    colors: { liquid: "#c87a3a", cap: "#2a1208", label: "#f5c28a" },
    sizes: [
      { ml: 30, price: 35000 },
      { ml: 50, price: 53000 },
      { ml: 100, price: 67000 },
    ],
    top: ["Cardamom", "Pink Peppercorn"],
    heart: ["Saffron", "Incense"],
    base: ["Leather", "Oud", "Amber"],
    description:
      "A royal procession of saffron and cardamom escorted by smoky incense and supple leather.",
  },
  {
    id: "fresh-10",
    name: "Linen Blanc",
    tagline: "Cotton Flower · Bergamot · Musk",
    category: "Clean",
    gender: "Unisex",
    price: 32000,
    oldPrice: 39000,
    badge: null,
    colors: { liquid: "#e8e2d0", cap: "#8a8273", label: "#ffffff" },
    sizes: [
      { ml: 30, price: 17000 },
      { ml: 50, price: 25000 },
      { ml: 100, price: 32000 },
    ],
    top: ["Bergamot", "Lemon Zest"],
    heart: ["Cotton Flower", "Freesia"],
    base: ["Clean Musk", "Blonde Woods"],
    description:
      "Sun-dried linen on a Provençal afternoon — cotton blossom and bergamot over cashmere musk.",
  },
  {
    id: "wood-11",
    name: "Santal Doré",
    tagline: "Sandalwood · Cardamom · Amber",
    category: "Woody",
    gender: "Unisex",
    price: 56000,
    oldPrice: null,
    badge: "New",
    colors: { liquid: "#d4a76a", cap: "#3d2914", label: "#f2dcb3" },
    sizes: [
      { ml: 30, price: 29500 },
      { ml: 50, price: 43500 },
      { ml: 100, price: 56000 },
    ],
    top: ["Cardamom", "Saffron"],
    heart: ["Australian Sandalwood", "Rose"],
    base: ["Amber", "Benzoin", "Musk"],
    description:
      "Honeyed Australian sandalwood gilded with amber and rose — warm, golden, and endlessly wearable.",
  },
  {
    id: "fig-12",
    name: "Figue Noire",
    tagline: "Black Fig · Almond Milk · Cedar",
    category: "Gourmand",
    gender: "Women",
    price: 43500,
    oldPrice: null,
    badge: null,
    colors: { liquid: "#7a4a4f", cap: "#261315", label: "#c89b9e" },
    sizes: [
      { ml: 30, price: 22500 },
      { ml: 50, price: 33500 },
      { ml: 100, price: 43500 },
    ],
    top: ["Black Fig", "Green Mandarin"],
    heart: ["Almond Milk", "Coconut Water"],
    base: ["Cedarwood", "Tonka"],
    description:
      "Ripe black figs cracked open on cedar — milky, creamy and quietly intoxicating.",
  },
];

window.CATEGORIES = [
  "All",
  "Oriental",
  "Floral",
  "Woody",
  "Citrus",
  "Aquatic",
  "Green",
  "Gourmand",
  "Clean",
];

window.GENDERS = ["All", "Women", "Men", "Unisex"];

// Price filter buckets in PKR
window.PRICE_BUCKETS = [
  { value: "all", label: "All prices" },
  { value: "0-35000", label: "Under Rs 35,000" },
  { value: "35000-55000", label: "Rs 35,000 – 55,000" },
  { value: "55000-999999", label: "Over Rs 55,000" },
];
